// ===============================
        // GAMES DATABASE - EDIT THIS ONLY!
        // ===============================
        const gamesDatabase = [
            // Add your games here - USE LOCAL IMAGES FROM "images" FOLDER
            {
                id: 1,
                name: "Assassin's Creed 1",
                genre: "Action Adventure,3D",
                category: "pc", // "pc" or "free"
                rating: 7.5,
                image: "images/Assassin Creed 1.jpg", // Local image in images folder
                description: "",
                requirements: [
                    "OS: Windows 7/8/10 64-bit",
                    "Processor:  Dual core processor 2.6 GHz Intel Pentium D or AMD Athlon™ 64 X2 3800+ (Intel Core® 2 Duo 2.2 GHz or AMD Athlon 64 X2 4400+ or better recommended)",
                    "Memory: 1 GB RAM",
                    "Graphics: 256 MB DirectX® 10.0-compliant video card",
                    "Storage: 8 GB available space"
                ],
                downloadLink: "",
                size: "2.5 GB",
                developer: "",
                releaseDate: "2007"
            },
            {
                id: 2,
                name: "Assassin's Creed 2",
                genre: "Action, Adventure",
                category: "pc",
                rating: 7.7,
                image: "images/Assassin Creed 2.jpg", // Local image in images folder
                description: "",
                requirements: [
                    "OS: Windows® XP (32-64 bits) /Windows Vista®(32-64 bits)",
"Processor: Intel Core® 2 Duo 1.8 GHZ or AMD Athlon X2 64 2.4GHZ",
"Memory: 1.5 GB Windows® XP / 2 GB Windows Vista® - Windows 7®",
"Graphics: 256 MB DirectX® 9.0–compliant card with Shader Model 3.0 or higher (see supported list)",
"DirectX®: DirectX 9.0",
"Hard Drive: 8 GB free space",
"Sound: DirectX 9.0 –compliant sound card"
                ],
                downloadLink: "",
                size: " 8 GB",
                developer: "",
                releaseDate: "2010"
            },
            {
                id: 3,
                name: "Assassin's Creed Brotherhood",
                genre: "Action,Adventure",
                category: "pc",
                rating: 8,
                image: "images/Assassin Creed Brotherhood.jpg", // Local image in images folder
                description: "",
                requirements: [
                    "OS: Windows® XP (32-64 bits) /Windows Vista®(32-64 bits)",
"Processor: Intel Core® 2 Duo 1.8 GHZ or AMD Athlon X2 64 2.4GHZ",
"Memory: 1.5 GB Windows® XP / 2 GB Windows Vista® - Windows 7®",
"Graphics: 256 MB DirectX® 9.0–compliant card with Shader Model 3.0 or higher (see supported list*)",
"DirectX®: 9.0",
"Hard Drive: 8 GB",
"Sound: DirectX 9.0 –compliant sound card"
                ],
                downloadLink: "",
                size: "6.5GB",
                developer: "",
                releaseDate: "2010-07-15"
            },
            {
                id: 4,
                name: "Grand Theft Auto V",
                genre: "Action,shooting",
                category: "pc",
                rating: 10,
                image: "images/GTA5.jpg", // Local image in images folder
                description: "",
                requirements: [
                    "OS: Windows 8.1 64 Bit, Windows 8 64 Bit, Windows 7 64 Bit Service Pack 1, Windows Vista 64 Bit Service Pack 2* (*NVIDIA video card recommended if running Vista OS)",
                    "Processor:  Intel Core 2 Quad CPU Q6600 @ 2.40GHz (4 CPUs) / AMD Phenom 9850 Quad-Core Processor (4 CPUs) @ 2.5GHz - actually works on dual-core CPUs as well",
                    "Memory: 4 GB RAM",
                    "Graphics: NVIDIA 9800 GT 1GB / AMD HD 4870 1GB (DX 10, 10.1, 11)",
                    "DirectX: 10",
                    "Storage: 90 available space"
                ],
                downloadLink: "",
                size: " 40 GB",
                developer: "Rockstar North, Rockstar San Diego, Rockstar Leeds, Rockstar Toronto, Rockstar New England, Rockstar London",
                releaseDate: "2015-04-14"
            },
            {
                id: 5,
                name: "Assassin's Creed Revelations",
                genre: "Action",
                category: "pc",
                rating: 8.4,
                image: "images/Assassin Creed Revelations.jpg", // Local image in images folder
                description: "",
                requirements: [
                    "OS: Windows XP / Windows Vista / Windows 7",
"CPU: Intel Core 2 Duo 2.8 GHz or AMD Athlon X2 Dual-Core 5200+",
"RAM: 2 GB",
"Video card: Nvidia Geforce 9800 или Radeon HD 4750",
"Hard disk space: 10 GB"
                ],
                downloadLink: "",
                size: "10 GB",
                developer: " Ubisoft Montreal",
                releaseDate: "11-10-01"
            },
            {
                id: 6,
                name: "Assassin's Creed III",
                genre: "FPS",
                category: "pc",
                rating: 8.3,
                image: "images/Assassin Creed 3.jpg", // Local image in images folder
                description: "",
                requirements: [
                    "Supported OS: Windows Vista (SP2) / Windows 7 (SP1) / Windows 8",
"Processor: 2.66 GHz Intel Core2 Duo E6700 or 3.00 GHz AMD Athlon 64 X2 6000+ or better recommended",
"RAM: 2 GB (4 GB recommended)",
"Video Card: 512 MB DirectX 9.0c-compliant with Shader Model 4.0 or higher (see supported list)",
"Sound Card: DirectX 9.0c-compliant (5.1 surround sound recommended)",
"DVD-ROM: Dual-layer drive",
"Hard Drive Space: 17 GB"
                ],
                downloadLink: "",
                size: "17 GB",
                developer: "Ubisoft Montreal",
                releaseDate: "2012-11-05"
            },
            {
                id: 7,
                name: "Assassin's Creed Liberation",
                 genre: "Action",
                 category: "pc",
                 rating: 5.0,
                 image: "images/Assassin Creed Liberation.jpg",
                 description: "",
                 requirements: [
                         "Operating system: Windows Vista SP2, Windows 7 SP1, Windows 8 / 8.1 (both 32 / 64bit versions)",
"Processor: Intel Core i3 2105 @ 3.1 GHz or AMD Phenom 2 X4 955 @ 3.2GHz",
"Memory: 2 GB",
"Graphics Card: Nvidia GeForce 8800GT or AMD Radeon HD4870 (512MB VRAM u0026 Shader Model 4.0)",
"Sound Card: Sound device compatible with DirectX® 9.0",
"Free space on hard drive: 3 GB"
                                  ],
                 downloadLink: "",
                 size: "File Size",
                 developer: "3 GB",
                 releaseDate: "2014"
            },
            {
                id: 8,
                name: "Assassin's Creed IV Black Flag",
                genre: "action",
                category: "pc",
                rating: 7.0,
                image: "images/Assassin Creed Black Flag.jpg",
                description: "",
                requirements: [
                    "OS: Windows Vista SP2 or Windows 7 SP1 or Windows 8 (both 32/64bit versions)",
                  "CPU: Intel Core2Quad Q8400 @ 2.6 GHz or AMD Athlon II X4 620 @ 2.6 GHz",
"RAM: 2 Gb",
"Video card: Nvidia Geforce GTX 260 or AMD Radeon HD 4870 (512MB VRAM with shader Model 4.0 or higher)",
                ],
                downloadLink: "",
                size: "15 GB",
                developer: "Ubisoft Montreal ",
                releaseDate: "October 29, 2013 "
            },
            {
                id: 9,
                name: "Assassin's Creed 3 Remastered",
                genre: "Action, Adventure",
                category: "pc",
                rating: 7.0,
                image: "images/Assassin Creed 3 Remastered.jpg",
                description: "",
                requirements: [
                    "Operating System: Windows 7 SP1, Windows 8.1, Windows 10 (64-bit versions only)",
"Processor: Intel Core i5 2400 @ 3.1 GHz, AMD FX 6350 @ 3.9 GHz",
"RAM: 8GB",
"Video Card: Nvidia GeForce GTX 660, AMD Radeon R9 270X (2GB VRAM with Shader Model 5.0)"
                ],
                downloadLink: "",
                size: " 43 GB",
                developer: "Ubisoft",
                releaseDate: "March 29th 2019"
            },
            {
                id: 10,
                name: "Assassin's Creed Odyssey",
                genre: "Action, Adventure",
                category: "pc",
                rating: 9.0,
                image: "images/Assassin Creed Odyssey.jpg",
                description: "",
                requirements: [
                    "Operating System: Windows 7 SP1, Windows 8.1, Windows 10 (64bit versions only)", 
"Processor: AMD FX 6300 @ 3.8 GHz, Ryzen 3 - 1200, Intel Core i5 2400 @ 3.1 GHz", 
"RAM: 8 GB", 
"Video Card: AMD Radeon R9 285, NVIDIA GeForce GTX 660 (2GB VRAM with Shader Model 5.0)",
"DirectX: 11", 
"HDD Space: 63 GB"],
                downloadLink: "",
                size: "63 GB",
                developer: "Ubisoft",
                releaseDate: "2018"
            },
            {
                id: 12,
                name: "Assassin's Creed Origin",
                genre: "Action, Adventure",
                category: "pc",
                rating: 4.0,
                image: "images/Assassin Creed Origin.jpg",
                description: "",
                requirements: [""],
                downloadLink: "",
                size: "",
                developer: "Ubisoft",
                releaseDate: ""
            },
            {
                id: 13,
                name: "Assassin's Creed Rogue",
                genre: "Action, Adventure",
                category: "pc",
                rating: 4.0,
                image: "images/Assassin Creed Rogue.jpg",
                description: "",
                requirements: [""],
                downloadLink: "",
                size: "",
                developer: "Ubisoft",
                releaseDate: ""
            },
            {
                id: 14,
                name: "Assassin's Creed Syndicate",
                genre: "Action, Adventure",
                category: "pc",
                rating: 4.0,
                image: "images/Assassin Creed Syndicate.jpg",
                description: "",
                requirements: [""],
                downloadLink: "",
                size: "",
                developer: "Ubisoft",
                releaseDate: ""
            },
            {
                id: 15,
                name: "Assassin's Creed Unity",
                genre: "Action, Adventure",
                category: "pc",
                rating: 4.0,
                image: "images/Assassin Creed Unity.jpg",
                description: "",
                requirements: [""],
                downloadLink: "",
                size: "",
                developer: "Ubisoft",
                releaseDate: ""
            },
            {
                id: 16,
                name: "Assassin's Creed valhalla",
                genre: "Action, Adventure",
                category: "pc",
                rating: 4.0,
                image: "images/Assassin Creed valhalla.jpg",
                description: "",
                requirements: [""],
                downloadLink: "",
                size: "",
                developer: "Ubisoft",
                releaseDate: ""
            },
            {
                id: 17,
                name: "FIFA 20",
                genre: "Sports, Soccer, Third-person, 3D",
                category: "pc",
                rating: 7.8,
                image: "images/FIFA 20 (2019).jpg",
                description: "",
                requirements: ["Operating System: Windows 7 (64-bit) / Windows 8.1 (64-bit) / Windows 10 (64-bit)",
"Processor: Intel Core i3-2100 or AMD Phenom II X4 965",
"RAM: 8 GB",
"Video Card: NVIDIA GeForce GTX 660 or AMD Radeon HD 7850, 2 GB",
"DirectX: 11",
"HDD Space: up to 55.6 GB"],
                downloadLink: "",
                size: "55.6 GB",
                developer: "EA Sports",
                releaseDate: "2019"
            },
            {
                id: 18,
                name: "Watch Dogs 2",
                genre: "",
                category: "pc",
                rating: 4.0,
                image: "images/watch dogs 2.jpg",
                description: "",
                requirements: [""],
                downloadLink: "",
                size: "",
                developer: "",
                releaseDate: ""
            },
            {
                id: 19,
                name: "Watch Dogs",
                genre: "",
                category: "pc",
                rating: 4.0,
                image: "images/watch dogs 2014.jpg",
                description: "",
                requirements: [""],
                downloadLink: "",
                size: "",
                developer: "",
                releaseDate: ""
            },
            {
                id: 20,
                name: "Watch Dogs Legion",
                genre: "",
                category: "pc",
                rating: 4.0,
                image: "images/watch dogs legion 2018.jpg",
                description: "",
                requirements: [""],
                downloadLink: "",
                size: "",
                developer: "",
                releaseDate: ""
            },
            {
                id: 21,
                name: "Euro Truck Simulator 2",
                genre: "Driving, Simulation, Open world, 3D",
                category: "pc",
                rating: 8.0,
                image: "images/Euro Truck Simulator 2 (2012).jpg",
                description: "",
                requirements: [
                    "Operating System: Windows 7",
"Processor: Dual core CPU 2.4 GHz",
"RAM: 4 GB",
"Video Card: GeForce GTS 450-class (Intel HD 4000)",
"DirectX: 9.0c",
"HDD Space: 30 GB"],
                downloadLink: "",
                size: "30 GB",
                developer: "SCS Software",
                releaseDate: ""
            },
            {
                id: 22,
                name: "Blur",
                genre: "Arcade / Racing (Cars) / 3D",
                category: "pc",
                rating: 7.0,
                image: "images/Blur.jpg",
                description: "",
                requirements: [
                    "Operating system : Windows XP (SP3), Windows Vista (SP2), Windows 7",
"Processor : Intel Core ® 2 Duo 3.4 GHz",
"Memory : 1 GB (2 GB for Vista / 7)",
"Video Card : 256 MB (NVIDIA GeForce 7800 level / Radeon X1800)",
"Sound Card : Sound device compatible with DirectX ® 9.0",
"Free space on hard disk : 8 GB"],
                downloadLink: "",
                size: "8 GB",
                developer: "Activision",
                releaseDate: "2010"
            },
            {
                id: 23,
                name: "Forza Horizon",
                genre: "Arcade, Racing, Open world, First-person, Third-person, Cars, 3D",
                category: "pc",
                rating: 4.0,
                image: "images/Forza Horizon (2012).jpg",
                description: "",
                requirements: [
                    "CPU: Intel Core i5-2500K 3.3GHz or AMD Phenom II X4 940.",
"GPU: NVIDIA GeForce GTX 660.",
"RAM: 6GB.",
"OS: 64-bit Windows 7 or 64-bit Windows 8 (8.1)",
"HDD Space: 10 GB.",
"DirectX 11."],
                downloadLink: "",
                size: "10GB",
                developer: "Turn 10 Studios, Playground Games",
                releaseDate: "23 October 2012"
            },
            {
                id: 24,
                name: "Forza Horizon 2 Presents Fast And Furious",
                genre: "Arcade, Racing, Open world, First-person, Third-person, Cars, 3D",
                category: "pc",
                rating: 6.0,
                image: "images/Forza Horizon 2 Presents Fast And Furious (2015).jpg",
                description: "",
                requirements: ["CPU. Core i5-9600K 6-Core 3.7GHz.", "GPU (10% overclock) GeForce GTX 1060 EVGA ACX 2.0 6GB.", "RAM. 16 GB.", "Resolution. 9200 x 1080"],
                downloadLink: "",
                size: "5GB",
                developer: "Turn 10 Studios, Playground Games",
                releaseDate: "2015"
            },
            {
                id: 25,
                name: "Forza Horizon 3",
                genre: "Arcade, Racing, Open world, First-person, Third-person, Cars, 3D",
                category: "pc",
                rating: 9.5,
                image: "images/Forza Horizon 3 (2016).jpg",
                description: "",
                requirements: [
                    "CPU: Intel i3-4170 @ 3.7Ghz OR Intel i5 750 @ 2.67Ghz",
"RAM: 8 GB",
"OS: Windows 10 version 15063.0 or higher",
"VIDEO CARD: NVidia 650TI OR NVidia GT 740 OR AMD R7 250x",
"PIXEL SHADER: 5.0",
"VERTEX SHADER: 5.0",
"DEDICATED VIDEO RAM: 2 GB"],
                downloadLink: "",
                size: "28 GB",
                developer: "Turn 10 Studios, Playground Games",
                releaseDate: "2016"
            },
            {
                id: 26,
                name: "Forza Horizon 4",
                genre: "Arcade, Racing, Open world, First-person, Third-person, Cars, 3D",
                category: "pc",
                rating: 9.6,
                image: "images/Forza Horizon 4 (2018).jpg",
                description: "",
                requirements: ["Requires 64-bit processor and operating system",
"OS: Windows 10 (1703 and higher)",
"Processor: Intel i3-4170 3.7Ghz / Intel i5 750 2.67Ghz",
"RAM: 4 GB of RAM",
"Video card: NVidia 650TI / AMD R7 250x, DirectX 12",
"Disk space: 95 GB"],
                downloadLink: "",
                size: "44 GB",
                developer: "Turn 10 Studios, Playground Games",
                releaseDate: "2018"
            },
            {
                id: 27,
                name: "Forza Horizon 5",
                genre: "Arcade, Racing, Open world, First-person, Third-person, Cars, 3D",
                category: "pc",
                rating: 100,
                image: "images/Forza Horizon 5 (2021).jpg",
                description: "",
                requirements: ["Requires 64-bit processor and operating system",
"OS: Windows 10 version 15063 and older",
"Processor: Intel i5-4460 / AMD Ryzen 3 1200",
"RAM: 8 GB of RAM",
"Video card: NVidia GTX 970 / AMD RX 470, DirectX 12",
"Disk space: 102 GB"],
                downloadLink: "",
                size: "102 GB",
                developer: "Turn 10 Studios, Playground Games",
                releaseDate: "2021"
            },
            {
                id: 28,
                name: "Forza Motorsport 7",
                genre: "Arcade, Racing, Open world, First-person, Third-person, Cars, 3D",
                category: "pc",
                rating: 9.2,
                image: "images/Forza Motorsport 7 (2017).jpg",
                description: "",
                requirements: ["Requires 64-bit processor and operating system",
"OS: Windows 10",
"Processor: Intel i5-750 2.67 GHz",
"RAM: 8 GB RAM",
"Video card: NVIDIA GT 740 or NVIDIA GTX 650 or AMD R7 250X, DirectX 12",
"Disk space: 90 GB"],
                downloadLink: "",
                size: "90 GB",
                developer: "Turn 10 Studios, Playground Games",
                releaseDate: "2017"
            },
            {
                id: 29,
                name: "Grand Theft Auto Vice City",
                genre: "Action, Shooting",
                category: "pc",
                rating: 9.7,
                image: "images/Grand Theft Auto Vice City (2002).jpg",
                description: "",
                requirements: ["Operating system: Windows Vista / Windows 7 / Windows 8 / Windows 10",
"Processor: Intel Pentium IV or equivalent AMD Athlon XP with a clock frequency of 1.5 GHz",
"RAM: 256 MB",
"Video card: NVIDIA GeForce 3 or ATI Radeon 8500 with 64 MB memory, compatible with DirectX®",
"Sound device: DirectX compatible",
"Hard disk space: 2 GB"],
                downloadLink: "",
                size: "2 GB",
                developer: "Rockstar Games",
                releaseDate: "13 May, 2003"
            },{
                id: 30,
                name: "Need for Speed Underground",
                genre: "Action, Adventure, Arcade, Co-op, Driving, Multiplayer, Open World, Racing, Simulation, Singleplayer",
                category: "pc",
                rating: 4.0,
                image: "images/Need for Speed Underground 2.jpg",
                description: "",
                requirements: ["Windows 98, 98 Second Edition ME 2000 Professional XP Professional or XP Home operating system","Intel Pentium III (or equivalent) CPU running at 933MHz or higher","32MB DirectX 9.0c compatible video card (Geforce2 or higher) using asupported chipset (see below)",
"256 MB RAM",
"DirectX compatible sound card 2 GB of HD space"],
                downloadLink: "",
                size: "2 GB",
                developer: "EA Black Box",
                releaseDate: "Nov 09, 2004"
            },
            {
                id: 31,
                name: "Red Dead Redemption 2",
                genre: "First-Person, Action, Shooting, 3D",
                category: "pc",
                rating: 10,
                image: "images/Red Dead Redemption 2 (2018).jpg",
                description: "",
                requirements: ["CPU: Intel Core i5-2500K / AMD FX-6300","RAM: 8 GB",
                "OS: Windows 7 SP1",
"Video Card: Nvidia GeForce GTX 770 2GB / AMD Radeon R9 280",
"Pixel Shader: 5.0",
"Vertex Shader: 5.0",
"Free Disk Space: 150 GB",
"Dedicated Video RAM: 2048 MB"],
                downloadLink: "",
                size: "150 GB",
                developer: "Rockstar Games",
                releaseDate: "2018"
            },
            {
                id: 32,
                name: "Far Cry 5",
                genre: " First-Person, Action, Shooting, 3D",
                category: "pc",
                rating: 8.9,
                image: "images/Far Cry 5 (2018).jpg",
                description: "",
                requirements: ["OS: Windows 7/8/8.1/10",
"CPU: Intel Core i5-2400 3.1 GHz / AMD FX-6300 3.5 GHz or equivalent",
"RAM: 8 GB RAM",
"Video card: NVIDIA GeForce GTX 670 or AMD R9 270 (2GB VRAM with Shader Model 5.0 or better)",
"Hard disk space: 30 GB"],
                downloadLink: "",
                size: "30 GB",
                developer: "",
                releaseDate: "2018"
            },
            {
                id: 33,
                name: "",
                genre: "",
                category: "pc",
                rating: 4.0,
                image: "images/",
                description: "",
                requirements: [""],
                downloadLink: "",
                size: "",
                developer: "",
                releaseDate: ""
            },
            {
                id: 11,
                name: "",
                genre: "",
                category: "pc",
                rating: 4.0,
                image: "images/",
                description: "",
                requirements: [""],
                downloadLink: "",
                size: "",
                developer: "",
                releaseDate: ""
            },





            // ADD MORE GAMES HERE - JUST COPY AND PASTE THE FORMAT!
            // {
            //     id: 7,
            //     name: "",
            //     genre: "",
            //     category: "pc", // OR "free"
            //     rating: 4.0,
            //     image: "images/",
            //     description: "",
            //     requirements: [
            //             
            //                      ],
            //     downloadLink: "",
            //     size: "File Size",
            //     developer: "",
            //     releaseDate: ""
            // }
        ];
